services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tech_challange_2
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data