services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: johnny
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: fiapdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: johnny
      DB_PASSWORD: senha123
      DB_NAME: fiapdb
    volumes:
      - .:/app

volumes:
  pgdata: